---
title: "internal 2"
author: "kranthi"
date: "4 November 2018"
output: html_document
---

```{r }
#loading liberaries
#library(stringr) #used for replacing the strings (str_replace)
#library(mlr) #used for creating dummies

```
```{r}
#loading the data

attrition <- read.csv("G:\\sem3\\HR analytics\\attrition.csv") 
attrition <- na.omit(attrition)
str(attrition)
summary(attrition)

```


```{r}
#replacing 2 categories with o and 1
attrition$DOJ.Extended <- str_replace(attrition$DOJ.Extended, "Yes","1")
attrition$DOJ.Extended <- str_replace(attrition$DOJ.Extended,"No", "0")
attrition$DOJ.Extended <- as.numeric(attrition$DOJ.Extended)

attrition$Joining.Bonus <- str_replace(attrition$Joining.Bonus, "Yes", "1")
attrition$Joining.Bonus <- str_replace(attrition$Joining.Bonus, "No","0")
attrition$Joining.Bonus <- as.numeric(attrition$Joining.Bonus)

attrition$Candidate.relocate.actual <- str_replace(attrition$Candidate.relocate.actual, "Yes", "1")
attrition$Candidate.relocate.actual<- str_replace(attrition$Candidate.relocate.actual, "No", "0")
attrition$Candidate.relocate.actual <- as.numeric(attrition$Candidate.relocate.actual)

attrition$Gender <- str_replace(attrition$Gender, "Female", "1")
attrition$Gender <- str_replace(attrition$Gender, "Male", "0")
attrition$Gender <- as.numeric(attrition$Gender)
str(attrition)

```
```{r}
#splitibg the data
set.seed(3)
ind <- sample(2, nrow(attrition), replace = TRUE, prob = c(0.7,0.3))
train <- attrition[ind == 1,]
#trainset
test <- attrition[ind == 2,]
#testset

```
```{r}
model <- glm(Status ~. , data =train, family = binomial)
summary(model)

```
```{r}
#fitting the model
fit = glm(Status ~ DOJ.Extended+Rex.in.Yrs+Age+Notice.period+Offered.band+Candidate.Source+LOB, data = train, family=binomial)
summary(fit)

```
```{r}
#install.packages("ResourceSelection")
library(ResourceSelection)
hoslem.test(train$Status, fitted(fit), g=10)

```

```{r}
pred12 <- predict(fit, type = "response", newdata = test[,1:16])
#pred
y_pred<- ifelse(pred12> 0.5,"Not Joined","Joined")

#y_pred
#y_pred <- cut(pred12, c(-Inf,0.5,Inf), labels=c("Not Joined","Joined"))
tb=table(test$Status,y_pred )
# Draw up confusion matrix
library(caret)
confusionMatrix(tb)
```
```{r}
library(ROCR)
predictions1 <- predict(fit, newdata=test, type="response")
ROCRpred <- prediction(predictions1, test$Status)
ROCRperf <- performance(ROCRpred, measure = "tpr", x.measure = "fpr")

#ploting roc
plot(ROCRperf, colorize = TRUE, text.adj = c(-0.2,1.7), print.cutoffs.at = seq(0,1,0.1))
```
```{r}
auc <- performance(ROCRpred, measure = "auc")
auc <- auc@y.values[[1]]
auc

```

```{r}
#install.packages("DAAG")
library(DAAG)
CVbinary(fit, nfolds = 10, print.details = TRUE)
```